# Generated by Django 5.2.5 on 2025-09-12 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.FloatField(default=0)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('authed', models.CharField(choices=[('Y', '인증됨'), ('N', '미인증')], default='N', max_length=1)),
                ('sns_type', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('E', '기타')], max_length=10, null=True)),
                ('prefer', models.CharField(max_length=100, null=True)),
                ('photo_url', models.CharField(default='/static/default_user.jpg', max_length=256)),
                ('last_ai', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.influencer')),
            ],
        ),
    ]
