# Generated by Django 5.2.5 on 2025-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='prefer_material',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
