# Generated by Django 5.2.5 on 2025-09-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_member_nickname_member_prefer_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='default', max_length=100, null=True),
        ),
    ]
