# Generated by Django 5.2.5 on 2025-09-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_member_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='voice_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
