# Generated by Django 5.2.5 on 2025-09-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_member_voice_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='survey_completed',
            field=models.BooleanField(default=False),
        ),
    ]
