# Generated by Django 5.2.5 on 2025-08-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginauth',
            old_name='authed_time',
            new_name='authed_at',
        ),
        migrations.RenameField(
            model_name='loginauth',
            old_name='due_time',
            new_name='expires_at',
        ),
    ]
