# Generated by Django 5.2.5 on 2025-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_rename_authed_time_loginauth_authed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginauth',
            name='cipher_key',
            field=models.CharField(max_length=44, null=True),
        ),
    ]
