# Generated by Django 5.2.5 on 2025-09-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talker_type', models.CharField(max_length=4)),
                ('style_text', models.TextField()),
                ('optional_text', models.TextField(blank=True, null=True)),
                ('voice_url', models.CharField(max_length=256, null=True)),
                ('talked_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='mainapp.influencer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-talked_at'],
            },
        ),
    ]
