# Generated by Django 5.2.5 on 2025-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_img_url', models.CharField(max_length=256)),
                ('persona', models.TextField(blank=True, null=True)),
                ('voice_info', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
