# Generated by Django 5.2.5 on 2025-09-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('spec', models.TextField(blank=True, null=True)),
                ('external_id', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('color_detail', models.TextField(blank=True, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('co2_saved_kg', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('water_saved_l', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_img_url', models.CharField(max_length=256)),
                ('persona', models.TextField(blank=True, null=True)),
                ('voice_info', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('look_style', models.CharField(blank=True, max_length=256, null=True)),
                ('look_img_url', models.CharField(blank=True, max_length=300, null=True)),
                ('look_desc', models.TextField(blank=True, null=True)),
                ('searched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='mainapp.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.appproduct')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.searchhistory')),
            ],
            options={
                'db_table': 'search_history_product',
            },
        ),
    ]
